'use client'

import { useQuery } from '@tanstack/react-query'
import { collection, doc, getDoc, getDocs } from 'firebase/firestore'
import { db } from '@lib/firebase-client'
import type { Line, Station, StationSchedule, StationTrips, MetraTripDetail } from '@ctt/shared'
import { displayStationName } from '@ctt/shared'

const ONE_DAY = 1000 * 60 * 60 * 24
/**
 * Schedule data is regenerated by the GTFS sync once an hour at most. The
 * card refreshes the rendered minutes-until on its own 60s timer; we only
 * want a fresh fetch every 30 minutes or so.
 */
const THIRTY_MINUTES = 1000 * 60 * 30

export function useLinesQuery() {
  return useQuery<Line[]>({
    queryKey: ['dashboard', 'lines'],
    queryFn: async () => {
      const snap = await getDocs(collection(db, 'lines'))
      return snap.docs.map((d) => {
        const line = d.data() as Line
        return {
          ...line,
          termini: (line.termini ?? []).map(displayStationName),
          downtownTerminal: displayStationName(line.downtownTerminal ?? null),
        }
      })
    },
    staleTime: ONE_DAY,
  })
}

export function useStationsQuery() {
  return useQuery<Station[]>({
    queryKey: ['dashboard', 'stations'],
    queryFn: async () => {
      const snap = await getDocs(collection(db, 'stations'))
      return snap.docs.map((d) => d.data() as Station)
    },
    staleTime: ONE_DAY,
  })
}

export function useStationScheduleQuery(slug: string | null) {
  return useQuery<StationSchedule | null>({
    queryKey: ['dashboard', 'station-schedule', slug],
    queryFn: async () => {
      if (!slug) return null
      const res = await fetch(`/api/schedules/${slug}`)
      if (res.status === 404) return null
      if (!res.ok) throw new Error(`Failed to load schedule: ${res.status}`)
      return (await res.json()) as StationSchedule
    },
    enabled: !!slug,
    staleTime: THIRTY_MINUTES,
  })
}

export function useStationTripsQuery(slug: string | null, enabled = true) {
  return useQuery<StationTrips | null>({
    queryKey: ['dashboard', 'station-trips', slug],
    queryFn: async () => {
      if (!slug) return null
      const res = await fetch(`/api/metra/station-trips/${slug}`)
      if (res.status === 404) return null
      if (!res.ok) throw new Error(`Failed to load station trips: ${res.status}`)
      return (await res.json()) as StationTrips
    },
    enabled: enabled && !!slug,
    staleTime: THIRTY_MINUTES,
  })
}

export function useFavoriteTripQuery(tripId: string | null) {
  return useQuery<MetraTripDetail | null>({
    queryKey: ['dashboard', 'metra-trip', tripId],
    queryFn: async () => {
      if (!tripId) return null
      const snap = await getDoc(doc(db, 'metra-trips', tripId))
      if (!snap.exists()) return null
      const trip = snap.data() as MetraTripDetail
      return {
        ...trip,
        headsign: displayStationName(trip.headsign),
        stops: (trip.stops ?? []).map((s) => ({
          ...s,
          stationName: displayStationName(s.stationName),
        })),
      }
    },
    enabled: !!tripId,
    staleTime: ONE_DAY,
  })
}
