import type { Line, Station, StationSchedule, StationTrips, NormalizedAlert } from '@ctt/shared'

export const mockLine: Line = {
  id: 'red',
  name: 'Red Line',
  shortName: 'Red',
  slug: 'red',
  service: 'cta',
  color: '#c60c30',
  textColor: '#ffffff',
  termini: ['Howard', '95th/Dan Ryan'],
  stationCount: 33,
  routeMiles: 23.0,
  operatesOvernight: true,
  type: 'rapid_transit',
  peakFrequencyMins: 3,
  offPeakFrequencyMins: 8,
  firstTrainApprox: '4:00 AM',
  lastTrainApprox: '1:00 AM',
  description: 'The busiest CTA line, running north–south through downtown.',
  ctaRouteId: 'Red',
  metraLineCode: null,
  downtownTerminal: null,
  operator: null,
  countiesServed: [],
  photoUrl: null,
  scheduleUrl: null,
}

export const mockMetraLine: Line = {
  id: 'bnsf',
  name: 'BNSF Railway',
  shortName: 'BNSF',
  slug: 'bnsf',
  service: 'metra',
  color: '#1A3D7A',
  textColor: '#ffffff',
  termini: ['Union Station', 'Aurora'],
  stationCount: 24,
  routeMiles: 37.0,
  operatesOvernight: false,
  type: 'commuter_rail',
  peakFrequencyMins: null,
  offPeakFrequencyMins: null,
  firstTrainApprox: '5:00 AM',
  lastTrainApprox: '11:30 PM',
  description: 'Metra BNSF line connecting Union Station to Aurora.',
  ctaRouteId: null,
  metraLineCode: 'BNSF',
  downtownTerminal: 'Union Station',
  operator: 'BNSF Railway',
  countiesServed: ['Cook', 'DuPage'],
  photoUrl: null,
  scheduleUrl: null,
}

export const mockStation: Station = {
  id: 'clark-lake',
  name: 'Clark/Lake',
  slug: 'clark-lake',
  address: '100 W Lake St, Chicago, IL',
  municipality: 'Chicago',
  location: { latitude: 41.8857, longitude: -87.6318 },
  service: 'cta',
  lines: ['Red', 'Blue', 'Green', 'Brown', 'Purple', 'Pink', 'Orange'],
  hours: { weekday: '24 hours', saturday: '24 hours', sunday: '24 hours' },
  open24Hours: true,
  terminal: false,
  parking: false,
  stationType: 'subway',
  accessibility: { ada: true, elevator: true, escalator: true },
  amenities: ['fare_vending', 'seating'],
  ctaStopId: 30074,
  ctaMapId: 40380,
  metraStopId: null,
  photoUrl: null,
  photoUrls: null,
  wikipediaUrl: null,
  metraLink: null,
  lineOrder: { Red: 12, Blue: 5 },
}

export const mockMetraStation: Station = {
  id: 'aurora',
  name: 'Aurora',
  slug: 'aurora',
  address: '233 N Broadway, Aurora, IL',
  municipality: 'Aurora',
  location: { latitude: 41.7606, longitude: -88.3201 },
  service: 'metra',
  lines: ['BNSF'],
  hours: null,
  open24Hours: false,
  terminal: true,
  parking: true,
  stationType: 'commuter_rail',
  accessibility: { ada: true, elevator: false, escalator: false },
  amenities: ['parking'],
  ctaStopId: null,
  ctaMapId: null,
  metraStopId: 'AURORA',
  photoUrl: null,
  photoUrls: null,
  wikipediaUrl: null,
  metraLink: 'https://metra.com/stations/aurora',
  lineOrder: { BNSF: 24 },
}

export const mockCtaAlert: NormalizedAlert = {
  id: '1',
  headline: 'Red Line Signal Work',
  description: 'Expect delays near Clark/Division',
  url: 'https://transitchicago.com/alert/1',
  routes: [{ routeId: 'Red', routeName: 'Red Line', color: '#c60c30', textColor: '#ffffff' }],
  severity: '25',
  isMajor: false,
  impact: 'Planned Work',
  startTime: '2026-04-01T00:00:00',
  endTime: null,
  service: 'cta',
}

export const mockMetraAlert: NormalizedAlert = {
  id: '2',
  headline: 'BNSF Delays',
  description: 'Expect delays due to construction',
  url: 'https://metrarail.com/alert/2',
  routes: [{ routeId: 'BNSF', routeName: 'BNSF Railway', color: '#1A3D7A', textColor: '#fff' }],
  severity: null,
  isMajor: false,
  impact: null,
  startTime: null,
  endTime: null,
  service: 'metra',
}

export const mockStationTrips: StationTrips = {
  weekday: [
    {
      tripId: 'BNSF_BN1200_V4_A',
      trainNumber: '1200',
      headsign: 'Chicago Union Station',
      departure: '5:30 AM',
      line: 'BNSF',
      lineSlug: 'bnsf',
      directionId: 1,
    },
    {
      tripId: 'BNSF_BN1205_V4_A',
      trainNumber: '1205',
      headsign: 'Aurora',
      departure: '6:00 AM',
      line: 'BNSF',
      lineSlug: 'bnsf',
      directionId: 0,
    },
    {
      tripId: 'BNSF_BN1210_V4_A',
      trainNumber: '1210',
      headsign: 'Chicago Union Station',
      departure: '6:30 AM',
      line: 'BNSF',
      lineSlug: 'bnsf',
      directionId: 1,
    },
  ],
  saturday: [
    {
      tripId: 'BNSF_BN2000_V4_A',
      trainNumber: '2000',
      headsign: 'Chicago Union Station',
      departure: '7:00 AM',
      line: 'BNSF',
      lineSlug: 'bnsf',
      directionId: 1,
    },
  ],
  sunday: [],
}

export const mockSchedule: StationSchedule = {
  directions: [
    {
      headsign: 'Howard',
      line: 'Red',
      weekday: [392, 435, 480, 720, 1425],
      saturday: [480, 600, 720],
      sunday: [540, 720],
    },
    {
      headsign: '95th/Dan Ryan',
      line: 'Red',
      weekday: [400, 445, 490, 730],
      saturday: [490, 610],
      sunday: [],
    },
  ],
}
