import type { Line, Station } from '@/app/lib/types'

export const mockLine: Line = {
  id: 'red',
  name: 'Red Line',
  shortName: 'Red',
  slug: 'red',
  service: 'cta',
  color: '#c60c30',
  textColor: '#ffffff',
  termini: ['Howard', '95th/Dan Ryan'],
  stationCount: 33,
  routeMiles: 23.0,
  operatesOvernight: true,
  type: 'rapid_transit',
  peakFrequencyMins: 3,
  offPeakFrequencyMins: 8,
  firstTrainApprox: '4:00 AM',
  lastTrainApprox: '1:00 AM',
  description: 'The busiest CTA line, running north–south through downtown.',
  ctaRouteId: 'Red',
  metraLineCode: null,
  downtownTerminal: null,
  operator: null,
  countiesServed: [],
  photoUrl: null,
  scheduleUrl: null,
}

export const mockMetraLine: Line = {
  id: 'bnsf',
  name: 'BNSF Railway',
  shortName: 'BNSF',
  slug: 'bnsf',
  service: 'metra',
  color: '#1A3D7A',
  textColor: '#ffffff',
  termini: ['Union Station', 'Aurora'],
  stationCount: 24,
  routeMiles: 37.0,
  operatesOvernight: false,
  type: 'commuter_rail',
  peakFrequencyMins: null,
  offPeakFrequencyMins: null,
  firstTrainApprox: '5:00 AM',
  lastTrainApprox: '11:30 PM',
  description: 'Metra BNSF line connecting Union Station to Aurora.',
  ctaRouteId: null,
  metraLineCode: 'BNSF',
  downtownTerminal: 'Union Station',
  operator: 'BNSF Railway',
  countiesServed: ['Cook', 'DuPage'],
  photoUrl: null,
  scheduleUrl: null,
}

export const mockStation: Station = {
  id: 'clark-lake',
  name: 'Clark/Lake',
  slug: 'clark-lake',
  address: '100 W Lake St, Chicago, IL',
  municipality: 'Chicago',
  location: { latitude: 41.8857, longitude: -87.6318 },
  service: 'cta',
  lines: ['Red', 'Blue', 'Green', 'Brown', 'Purple', 'Pink', 'Orange'],
  hours: { weekday: '24 hours', saturday: '24 hours', sunday: '24 hours' },
  open24Hours: true,
  terminal: false,
  parking: false,
  stationType: 'subway',
  accessibility: { ada: true, elevator: true, escalator: true },
  amenities: ['fare_vending', 'seating'],
  ctaStopId: 30074,
  ctaMapId: 40380,
  metraStopId: null,
  photoUrl: null,
  wikipediaUrl: null,
  metraLink: null,
  lineOrder: { Red: 12, Blue: 5 },
}

export const mockMetraStation: Station = {
  id: 'aurora',
  name: 'Aurora',
  slug: 'aurora',
  address: '233 N Broadway, Aurora, IL',
  municipality: 'Aurora',
  location: { latitude: 41.7606, longitude: -88.3201 },
  service: 'metra',
  lines: ['BNSF'],
  hours: null,
  open24Hours: false,
  terminal: true,
  parking: true,
  stationType: 'commuter_rail',
  accessibility: { ada: true, elevator: false, escalator: false },
  amenities: ['parking'],
  ctaStopId: null,
  ctaMapId: null,
  metraStopId: 'AURORA',
  photoUrl: null,
  wikipediaUrl: null,
  metraLink: 'https://metra.com/stations/aurora',
  lineOrder: { BNSF: 24 },
}
